name: GithubActions CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Merge feature branches
      run: ./script/merge-feature-branches

    - name: Build application
      #run: ./gradlew build
      #run: ./gradlew assembleRelease
      run: ./gradlew assembleCiRelease
    - name: Archive APKs
      uses: actions/upload-artifact@v3
      with:
        name: outputs-apk
        path: app/build/outputs/apk/**/*.apk

    - name: Run tests
      run: ./gradlew testCiRelease
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: outputs-tests
        path: app/build/test-results

    - name: Static analysis
      run: ./gradlew lint
    - name: Archive lint results
      uses: actions/upload-artifact@v3
      with:
        name: outputs-lint
        path: app/build/reports/lint-*

  pre-release:
    if: (github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/pre-release-permission')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve built assets
      uses: actions/download-artifact@v3
      with:
        name: outputs-apk
        path: app/build/outputs/apk
    - name: Publish assets
      permissions:
        contents: write # Needed to manipulate tags
      # Pre-release the built apps and expose it via a static and public accessible URL
      # Note that this step exists since artifacts (actions/upload-artifact) are neither
      # public-accessible nor at a constant/static URL
      # For the pre-releasing purpose, a floating tag is used and re-positioned to the tip of the branch
      uses: pyTooling/Actions/releaser@r0
      with:
        tag: pre-release
        token: ${{ secrets.GITHUB_TOKEN }}
        rm: true # clean past assets
        files: |
          app/build/outputs/apk/**/*.apk
